services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: >
      azurite --blobHost 0.0.0.0
              --queueHost 0.0.0.0
              --tableHost 0.0.0.0
              --location /data
              --skipApiVersionCheck
    environment:
      AZURITE_ACCOUNTS: "devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
    volumes:
      - azurite-data:/data

  cippapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FUNCTIONS_WORKER_RUNTIME: powershell
      FUNCTIONS_WORKER_RUNTIME_VERSION: "7.4"
      FUNCTIONS_EXTENSION_VERSION: "~4"
      AzureFunctionsJobHost__Logging__Console__IsEnabled: "true"
      NonLocalHostAzurite: "true"
      WEBSITE_HOSTNAME: cippapi

      AzureWebJobsStorage: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;"

      ApplicationID: ${ApplicationID}
      ApplicationSecret: ${ApplicationSecret}
      RefreshToken: ${RefreshToken}
      TenantID: ${TenantID}
    depends_on:
      - azurite

  cippapi-nginx:
    image: nginx:alpine
    depends_on:
      - cippapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "80"
    labels:
      - coolify.managed=true

volumes:
  azurite-data:
