services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: >
      azurite --blobHost 0.0.0.0
              --queueHost 0.0.0.0
              --tableHost 0.0.0.0
              --location /data
              --skipApiVersionCheck
    volumes:
      - azurite-data:/data

  cippapi:
    build:
      context: ./CIPP-API
      dockerfile: Dockerfile
    environment:
      FUNCTIONS_WORKER_RUNTIME: powershell
      FUNCTIONS_WORKER_RUNTIME_VERSION: "7.4"
      FUNCTIONS_EXTENSION_VERSION: "~4"
      AzureWebJobsStorage: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM...;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      WEBSITES_HOSTNAME: cippapi
      WEBSITE_HOSTNAME: cippapi
      AzureWebJobsFeatureFlags: EnableWorkerIndexing
      NonLocalHostAzurite: "true"

      ApplicationID: ${ApplicationID}
      ApplicationSecret: ${ApplicationSecret}
      RefreshToken: ${RefreshToken}
      TenantID: ${TenantID}

    depends_on:
      - azurite

  frontend:
    build:
      context: ./CIPP
      dockerfile: Dockerfile
    depends_on:
      - cippapi

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - cippapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "80"
    labels:
      - coolify.managed=true

volumes:
  azurite-data:
