services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"

  web-proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    depends_on:
      - web
    expose:
      - "80"
    labels:
      - coolify.managed=true